version: "2.2"

services:
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"

  auth-service:
    depends_on:
      - database
    links:
      - "database"
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  user-service:
    depends_on:
      - database
    links:
      - "database"
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  education-service:
    depends_on:
      - database
    links:
      - "database"
    build:
      context: ../education-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"