version: "2.2"

services:
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  education-service:
    build:
      context: ../education-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  
  survey-service:
    build:
      context: ../survey-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  goal-service:
    build:
      context: ../goal-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"